{{- $a := .Values.auth -}}
{{- if or $a.encryptedBasicAuthEmail $a.encryptedBasicAuthPassword $a.encryptedGitUser $a.encryptedGitToken -}}
{{- $labels := dict
  "app.kubernetes.io/name" "kestra"
  "app.kubernetes.io/instance" .Release.Name
  "app.kubernetes.io/part-of" "kestra"
  "app.kubernetes.io/managed-by" .Release.Service -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kestra-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml $labels | nindent 4 }}
spec:
  encryptedData:
    {{- with $a.encryptedBasicAuthEmail }}
    basicAuthEmail: {{ . | quote }}
    {{- end }}
    {{- with $a.encryptedBasicAuthPassword }}
    basicAuthPassword: {{ . | quote }}
    {{- end }}
    {{- with $a.encryptedGitUser }}
    gitUser: {{ . | quote }}
    {{- end }}
    {{- with $a.encryptedGitToken }}
    gitToken: {{ . | quote }}
    {{- end }}
  template:
    metadata:
      name: kestra-auth
      namespace: {{ .Release.Namespace }}
      labels:
        {{- toYaml $labels | nindent 8 }}
    type: Opaque
{{- end }}
