{{- if and .Values.git.enabled .Values.git.auth.enabled .Values.git.auth.encryptedUsername .Values.git.auth.encryptedPassword -}}
{{- $labels := dict
  "app.kubernetes.io/name" "kestra"
  "app.kubernetes.io/instance" .Release.Name
  "app.kubernetes.io/part-of" "kestra"
  "app.kubernetes.io/managed-by" .Release.Service -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kestra-git-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml $labels | nindent 4 }}
spec:
  encryptedData:
    username: {{ .Values.git.auth.encryptedUsername | quote }}
    password: {{ .Values.git.auth.encryptedPassword | quote }}
  template:
    metadata:
      name: kestra-git-auth
      namespace: {{ .Release.Namespace }}
      labels:
        {{- toYaml $labels | nindent 8 }}
    type: Opaque
{{- end }}
